# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8c8357074fd49bb5bd41d38f8cf0d5845b072aec31257f5cf18381284d61316c1bc59ea82123e566b79024f2151fd1a1d58b79b0b3adc7fbc694aa8512b75e2

test:
  secret_key_base: af622580fee1daf043232292fc81afb18759a23601dc73b1f6ec339064f43c558ad06c181733ef27395e8fe945a03da00f6045a7e02fbfc2a596ce4bba451f4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
